set(sources
src/CaloHitContribution.cc
src/CaloHitContributionCollection.cc
src/CaloHitContributionConst.cc
src/CaloHitContributionObj.cc
src/CaloHitContributionSIOBlock.cc
src/CalorimeterHit.cc
src/CalorimeterHitCollection.cc
src/CalorimeterHitConst.cc
src/CalorimeterHitObj.cc
src/CalorimeterHitSIOBlock.cc
src/Cluster.cc
src/ClusterCollection.cc
src/ClusterConst.cc
src/ClusterObj.cc
src/ClusterSIOBlock.cc
src/EventHeader.cc
src/EventHeaderCollection.cc
src/EventHeaderConst.cc
src/EventHeaderObj.cc
src/EventHeaderSIOBlock.cc
src/MCParticle.cc
src/MCParticleCollection.cc
src/MCParticleConst.cc
src/MCParticleObj.cc
src/MCParticleSIOBlock.cc
src/MCRecoCaloAssociation.cc
src/MCRecoCaloAssociationCollection.cc
src/MCRecoCaloAssociationConst.cc
src/MCRecoCaloAssociationObj.cc
src/MCRecoCaloAssociationSIOBlock.cc
src/MCRecoParticleAssociation.cc
src/MCRecoParticleAssociationCollection.cc
src/MCRecoParticleAssociationConst.cc
src/MCRecoParticleAssociationObj.cc
src/MCRecoParticleAssociationSIOBlock.cc
src/MCRecoTrackerAssociation.cc
src/MCRecoTrackerAssociationCollection.cc
src/MCRecoTrackerAssociationConst.cc
src/MCRecoTrackerAssociationObj.cc
src/MCRecoTrackerAssociationSIOBlock.cc
src/ParticleID.cc
src/ParticleIDCollection.cc
src/ParticleIDConst.cc
src/ParticleIDObj.cc
src/ParticleIDSIOBlock.cc
src/RawCalorimeterHit.cc
src/RawCalorimeterHitCollection.cc
src/RawCalorimeterHitConst.cc
src/RawCalorimeterHitObj.cc
src/RawCalorimeterHitSIOBlock.cc
src/ReconstructedParticle.cc
src/ReconstructedParticleCollection.cc
src/ReconstructedParticleConst.cc
src/ReconstructedParticleObj.cc
src/ReconstructedParticleSIOBlock.cc
src/RecoParticleRef.cc
src/RecoParticleRefCollection.cc
src/RecoParticleRefConst.cc
src/RecoParticleRefObj.cc
src/RecoParticleRefSIOBlock.cc
src/SimCalorimeterHit.cc
src/SimCalorimeterHitCollection.cc
src/SimCalorimeterHitConst.cc
src/SimCalorimeterHitObj.cc
src/SimCalorimeterHitSIOBlock.cc
src/SimpleTrackerHit.cc
src/SimpleTrackerHitCollection.cc
src/SimpleTrackerHitConst.cc
src/SimpleTrackerHitObj.cc
src/SimpleTrackerHitSIOBlock.cc
src/SimTrackerHit.cc
src/SimTrackerHitCollection.cc
src/SimTrackerHitConst.cc
src/SimTrackerHitObj.cc
src/SimTrackerHitSIOBlock.cc
src/TPCHit.cc
src/TPCHitCollection.cc
src/TPCHitConst.cc
src/TPCHitObj.cc
src/TPCHitSIOBlock.cc
src/Track.cc
src/TrackCollection.cc
src/TrackConst.cc
src/TrackerHit.cc
src/TrackerHitCollection.cc
src/TrackerHitConst.cc
src/TrackerHitObj.cc
src/TrackerHitSIOBlock.cc
src/TrackObj.cc
src/TrackSIOBlock.cc
src/Vertex.cc
src/VertexCollection.cc
src/VertexConst.cc
src/VertexObj.cc
src/VertexSIOBlock.cc
)
